export const UPLOAD_EDIT_DELETE_DATA = 'UPLOAD_EDIT_DELETE_DATA';
export const START_UPLOAD_EDIT_DELETE_DATA = 'START_UPLOAD_EDIT_DELETE_DATA';
export const ERROR_UPLOAD_EDIT_DELETE_DATA = 'ERROR_UPLOAD_EDIT_DELETE_DATA'
export const UPLOAD_EDIT_DELETE_DATA_SUCESS = 'GET_SAVE_DATA_SUCESS';